import {useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import type {Ledger,Status} from './types';
import {defaults} from './data/defaults';
import {calculate,profileAt,validate} from './utils/ledger';
import {expenses} from './utils/expense';
import {duration,dateInput,range,yearBounds} from './utils/time';
import {read,save,online} from './store';
import {Account} from './components/Account';
import './style.css';
import {SettingsModal} from './components/SettingsModal';
import {cashAdjustments} from './utils/cashflow';
const uid=()=>crypto.randomUUID();
const money=(n:number)=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',maximumFractionDigits:2}).format(Math.abs(n));
const signed=(n:number)=>(n<0?'−':'+')+money(n);
const names={working:'工作中',unemployed:'待业中',paused:'休息中'};
function App(){const [error,setError]=useState('');const inFlight=useRef(false);const [l,setL]=useState<Ledger|null>(()=>{try{return read()}catch{return null}});const [now,setNow]=useState(Date.now());const [settings,setSettings]=useState(false);const [details,setDetails]=useState(false);const [amount,setAmount]=useState('');const [note,setNote]=useState('');const [entryKind,setEntryKind]=useState<'income'|'expense'>('expense');useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);async function commit(next:Ledger){if(inFlight.current)return false;inFlight.current=true;try{await save(next);setL(next);setNow(Date.now());setError('');return true}catch(err){setError(String(err));return false}finally{inFlight.current=false}}
function importFile(file:File|undefined){if(file)file.text().then(raw=>{try{const data=validate(JSON.parse(raw));if(confirm('用备份恢复当前账本？'))commit(data)}catch(err){setError('备份无法读取：'+String(err))}})}
if(!l)return <main className="welcome"><div className="brand">◷ 时间账户</div><h1>没工作的时候，<br/>时间值多少钱？</h1><p>只填一个大致月薪，就能开始。不用每天记账。</p><form onSubmit={ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget),salary=Number(f.get('salary'))||6000,start=new Date(String(f.get('start'))+'T00:00:00').getTime();commit({version:1,initialSalary:salary,birthday:'',referenceAge:80,profiles:[defaults(start)],events:[],periods:[{id:uid(),type:f.get('state') as Status,startAt:start,endAt:null,targetSalary:salary,actualSalary:salary,expenseReferenceIncome:salary,company:'',jobTitle:'',countOpportunity:false}]})}}><label>参考月薪<input name="salary" type="number" min="1" defaultValue="6000"/></label><label>当前状态<select name="state"><option value="unemployed">没有工作</option><option value="working">正在工作</option><option value="paused">主动休息</option></select></label><label>从哪天开始<input name="start" type="date" required max={dateInput(now)} defaultValue={dateInput(now)}/></label><button className="primary">开始计时 →</button></form><label className="import">恢复已有备份<input type="file" accept=".json" onChange={ev=>importFile(ev.target.files?.[0])}/></label>{error&&<p className="error">{error}</p>}<footer>{online?'数据保存在在线账户 · 跨设备使用':'仅在本机保存 · 关闭网页后，下次打开自动补算'}</footer></main>;
const current=[...l.periods].sort((a,b)=>b.startAt-a.startAt).find(p=>p.startAt<=now&&(p.endAt===null||p.endAt>now));const state=current?.type??'paused';const salary=current?.targetSalary||l.initialSalary;const profile=profileAt(l,now);const monthly=expenses(current?.expenseReferenceIncome||salary,profile);const [ys,ye]=yearBounds(new Date(now).getFullYear());const perSecond=salary*12/(ye-ys)*1000;const entries=l.extras??[];function sums(scope:string){const [start,end]=range(scope,now);const v=calculate(l!,start,end);const cash=cashAdjustments(entries,start,end);return {...v,extra:cash.expense,extraIncome:cash.income,display:v.income-v.social-v.fund-v.tax-v.opportunity+cash.net}}const day=sums('今天'),month=sums('本月'),all=sums('全部');const pending=state==='unemployed'||current?.countOpportunity;const rate=state==='working'?(current?.actualSalary||salary)*12/(ye-ys)*1000:pending?-perSecond:0;
function transition(type:Status){const t=Date.now();commit({...l!,periods:[...l!.periods.map(p=>p.id===current?.id?{...p,endAt:t}:p),{id:uid(),type,startAt:t,endAt:null,targetSalary:salary,actualSalary:current?.actualSalary||salary,expenseReferenceIncome:current?.expenseReferenceIncome||salary,company:'',jobTitle:'',countOpportunity:false}],events:[...l!.events,{id:uid(),timestamp:t,type:'状态变更',payload:type}]})}
return <main className="dashboard"><header><div className="brand">◷ <span>时间账户<small>TIME LEDGER</small></span></div><div className="header-actions"><span className="date">{new Date(now).toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}</span><button className="quiet" onClick={()=>setSettings(!settings)}>设置</button></div></header>{error&&<p className="error" role="alert">{error}</p>}
<section className="counter"><div className="status"><i/>{names[state]}<span>已持续 {duration(now-(current?.startAt??now))}</span></div><p className="eyebrow">今天 · 收入与支出的变化</p><div className={'big-number '+(day.display<0?'negative':'positive')}>{signed(day.display)}</div><div className="totals"><span>当月 <b>{signed(month.display)}</b></span><i/><span>累计 <b>{signed(all.display)}</b></span></div><div className="second"><span>{state==='working'?'每秒产生的税前收入':pending?'待业每经过一秒，对应未实现收入':'休息期间暂停机会成本'}</span><strong>{rate<0?'−':'+'}¥{Math.abs(rate).toFixed(6)}<small> / 秒</small></strong></div><p className="explanation">{state==='working'?'金额 = 估算到手收入 + 额外收入 − 收入机会成本 − 额外支出。生活成本在下方独立显示，工作收入与过去机会成本仍分别保留。':'待业金额 = 额外收入 − 未实现收入 − 额外支出。额外收入不会清除已累计的机会成本。机会成本是参考月薪折算的时间价值，不是实际扣款；生活成本单独显示。'}</p><div className="state-actions"><button onClick={()=>transition(state==='working'?'unemployed':'working')}>{state==='working'?'我离职了':'我找到工作了'} ↗</button><button className="quiet" onClick={()=>transition(state==='paused'?'unemployed':'paused')}>{state==='paused'?'开始待业计时':'主动休息，暂停计时'}</button></div></section>
<section className="extra-panel"><div><h2>额外收支，随手加一笔。</h2><p>兼职、零工、奖励，或预算外的临时支出。只需填金额。</p></div><div className="cash-tabs"><button type="button" className={entryKind==='income'?'selected':''} aria-pressed={entryKind==='income'} onClick={()=>setEntryKind('income')}>额外收入 ＋</button><button type="button" className={entryKind==='expense'?'selected':''} aria-pressed={entryKind==='expense'} onClick={()=>setEntryKind('expense')}>额外支出 −</button></div><form onSubmit={async ev=>{ev.preventDefault();const n=Number(amount);if(!Number.isFinite(n)||n<=0)return;if(await commit({...l,extras:[...entries,{id:uid(),timestamp:Date.now(),amount:n,kind:entryKind,note:note.trim()||(entryKind==='income'?'额外收入':'额外支出')}]})){setAmount('');setNote('')}}}><div className="amount-input"><span>¥</span><input aria-label={entryKind==='income'?'额外收入金额':'额外支出金额'} type="number" step="0.01" min="0.01" required placeholder="金额" value={amount} onChange={ev=>setAmount(ev.target.value)}/></div><input aria-label="收支备注" placeholder="备注，可不填" value={note} onChange={ev=>setNote(ev.target.value)} maxLength={100}/><button className="primary">{entryKind==='income'?'加到今天 ＋':'加到今天 −'}</button></form><p className="extra-tip">今天额外收入 +{money(day.extraIncome)} · 额外支出 −{money(day.extra)} · 不重复计入生活预算</p>{entries.length>0&&<div className="entries">{[...entries].reverse().slice(0,5).map(entry=><div key={entry.id}><span>{dateInput(entry.timestamp)} · {entry.note}</span><b className={entry.kind==='income'?'cash-positive':''}>{entry.kind==='income'?'+':'−'}{money(entry.amount)}</b><button className="quiet" onClick={()=>commit({...l,extras:entries.filter(e=>e.id!==entry.id)})}>撤销</button></div>)}</div>}</section>
<div className="support"><div><span>参考月薪</span><strong>{money(salary)}</strong><small>日历时间价值 {money(perSecond*3600)} / 小时</small></div><div><span>今日预计生活成本</span><strong>−{money(day.cost)}</strong><small>待业也会发生，独立于主计数</small></div><div><span>每月生活预算</span><strong>−{money(monthly.total)}</strong><small>{monthly.rows[0].fixed!==undefined?'含手动房租':'全部使用默认估算'} · 无需逐项填写</small></div></div>
<button className="detail-toggle" onClick={()=>setDetails(!details)}>{details?'收起':'查看'}明细与历史 {details?'−':'+'}</button>{details&&<section className="details"><div className="summary"><div><span>累计收入机会成本</span><b>−{money(all.opportunity)}</b></div><div><span>累计税前工作收入</span><b>+{money(all.income)}</b></div><div><span>累计预计生活成本</span><b>−{money(all.cost)}</b></div><div><span>累计额外收入</span><b className="cash-positive">+{money(all.extraIncome)}</b></div><div><span>累计额外支出</span><b>−{money(all.extra)}</b></div></div><h2>生活预算 · 默认估算</h2><div className="budget">{monthly.rows.map(r=><div key={r.name}><span>{r.name}<small>{r.source}</small></span><b>{money(r.amount)}</b></div>)}</div><h2>职业时间线</h2>{[...l.periods].reverse().map(p=><div className="history" key={p.id}><span>{dateInput(p.startAt)} → {p.endAt?dateInput(p.endAt):'现在'}</span><b>{names[p.type]}</b><span>{money(p.targetSalary)} / 月</span></div>)}<p className="explanation">过去的机会成本永久保留，工作收入独立统计。所有时间金额均从已保存的时间戳重新计算。</p></section>}
{settings&&<SettingsModal onClose={()=>setSettings(false)}><section className="settings"><h2>只改你知道的。</h2><p>工资必填，其余留空即可。修改从此刻生效，过去的数据保留。</p><form onSubmit={async ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget),n=Number(f.get('salary'))||6000,t=Date.now(),p=JSON.parse(JSON.stringify(profile));p.id=uid();p.effectiveFrom=t;p.expenses[0].fixed=f.get('rent')===''?undefined:Number(f.get('rent'));const next={...l,initialSalary:n,profiles:[...l.profiles,p],periods:[...l.periods.map(x=>x.id===current?.id?{...x,endAt:t}:x),{id:uid(),type:state,startAt:t,endAt:null,targetSalary:n,actualSalary:n,expenseReferenceIncome:state==='working'?n:current?.expenseReferenceIncome||n,company:'',jobTitle:'',countOpportunity:current?.countOpportunity??false}],events:[...l.events,{id:uid(),timestamp:t,type:'修改工资与房租',payload:{salary:n,rent:p.expenses[0].fixed}}]};if(await commit(next))setSettings(false)}}><label>参考月薪<input name="salary" type="number" min="1" defaultValue={salary} required/></label><label>每月房租（可不填）<input name="rent" type="number" min="0" defaultValue={profile.expenses[0].fixed} placeholder="留空自动估算"/></label><button className="primary">保存</button></form><div className="backup"><button onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(l,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`时间账户-${dateInput(now)}.json`;a.click();URL.revokeObjectURL(url)}}>备份数据</button><label className="import">恢复备份<input type="file" accept=".json" onChange={ev=>{importFile(ev.target.files?.[0]);ev.target.value=''}}/></label></div>{error&&<p className="error" role="alert">{error}</p>}</section></SettingsModal>}
<footer><span><i/> {online?'账本保存在服务器 · 同一账号跨设备使用':'所有数据仅保存在本机'}</span><span>关闭网页后，时间继续。下次打开自动补算。</span></footer></main>}
createRoot(document.getElementById('root')!).render(<Account><App/></Account>);
